### PR TITLE
adding Big Cartel and Gumroad buttons

### PR DESCRIPTION
**Pull request by sedomu**
Big Cartel and Gumroad are well-known e-commerce platforms dedicated to artists, mainly.

Big Cartel's svg drawn according to their official brand guide (https://www.bigcartel.com/resources/help/article/brand-guide)
Gumroad's svg edited from the miniature in the bottom of their front page (https://gumroad.com/)

### CODE REVIEW

**Comment by penglezos** [comment]
I think it's a better fit for: https://github.com/sethcottle/littlelink-extended

**Comment by sedomu** [comment]
ok, I'll prepare a new pull request on extended.
Just to show I was compliant with the rules for new entries, I checked beforehand the popularity for these sites I'm used to see in bios on Instagram they were at the same level of popularity than other buttons available on main. But maybe it's too close from the bottom tier.
Capture d’écran 2024-04-02 à 18 41 38
Capture d’écran 2024-04-02 à 18 48 20

**Comment by sethcottle** [comment]
Thanks @sedomu! Sorry for the late response on this, I was out of pocket all weekend. I think the main repo is in need of a little purge to move some things over to Extended that made it in the last few years, I'm going to add that to my to-do list for this upcoming week.

**Comment by sedomu** [comment]
ok, that's clear(er) 👍

**Pull request closed without merging**
