### PR TITLE
Added Cash App and Auto Theme

### PR DESCRIPTION
**Pull request by EEkebin**
Added in Cash App style.

Added in Logo:
 - Cash App Dollar.
 - Cash App Pound.
 - Cash App BTC.

Added in logos for each button in index.html.

### CODE REVIEW

**Comment by EEkebin** [comment]
Sorry, my end of file line endings didn't make it through to the commit due to a bug on my end.
Ended up adding them in manually using GitHub.
Hope this doesn't affect the pull requests acceptance.

**Comment by sethcottle** [comment]
First off, great addition, thank you! Though before approving, I would recommend either changing the CSS brand color for the button to be either black or white **or** convert the iconography to be white so that it stands out from the green button. Attaching the screenshot here of what your addition to `index.html` looks like and the icons just blend in with the brand styling making the white middle portions of the icons seem very small, even though the icon itself is the same size. :)

image

**Comment by EEkebin** [comment]
I got rid of the green frame of the Icon and made the white Dollar, Pound, and BTC Symbols as big as they can become staying within the same canvas size. This makes the icon bigger now and makes it stand out more. I've taken a look at a white/black version of the styles but the contrast of the white makes it blend in on a white theme and the black is bad on a black theme. It kind of looks out of place for a Cash App logo as well. I think it looks good with my [latest commit](https://github.com/sethcottle/littlelink/pull/40/commits/5a6b21b64673f0492231e140c700f93b47c53eb4).

**Comment by EEkebin** [comment]
As for my latest addition/commit, I've also added in an Auto Theme and updated the Dark Theme's background color to match the html standard/recommended #121212 that skeleton-auto.css uses now. I have also made comments on how to switch to enforce a color scheme and made auto the default. Let me know what you think.

I do apologize for not splitting the 2 into their own pull requests, but I continued to edit this one since I believe if both got accepted, one would overwrite the other and cause a mismatch of versions.

**Pull request merged**
