### PR TITLE
Add Devpost Icon and Button

### PR DESCRIPTION
**Pull request by MoritzHayden**
Adds support for [Devpost](https://devpost.com/).

### CODE REVIEW

**Comment by sethcottle** [comment]
Hey @MoritzHayden! Thanks for the pull request! I would likely say Devpost might need to stay in the "make your own" category for now! While I know there is popularity within the dev community with Devpost, one of our core goals is to keep our defaults to globally or at least regionally popular services that are traffic heavy and would be a value add for the majority of those using LittleLink instead of a handful. This is to mostly help first-time users not be presented with an overwhelming number of services to parse through. 

Totally open to your thoughts around this though! I often check a lot of the forks that get made of LittleLink to see what other services users are adding on their own and haven't ran across one with Devpost as of yet. [Wiki page on submitting brands](https://github.com/sethcottle/littlelink/wiki/Submitting-a-new-brand-to-LittleLink).

**Comment by MoritzHayden** [comment]
@sethcottle Sure, no problem! I had implemented it in my own repo and figured I'd make a pull request just in case someone else wanted to use it.

**Comment by sethcottle** [comment]
Hey @MoritzHayden ! This morning I published [LittleLink Extended](https://github.com/sethcottle/littlelink-extended). This is a separate repository from LittleLink where more niche services can be published in the new `brands-extended.css` file to help LittleLink users discover and add more services to their copy LittleLink without cluttering the core repository.

Take a look over at https://github.com/sethcottle/littlelink-extended. If you'd like to add Devpost, please feel free. Or just throw a comment here and I'll add Devpost for you! 

Thanks again!

**Comment by MoritzHayden** [comment]
@sethcottle Feel free to copy it over if you'd like!

**Pull request closed without merging**
