### PR TITLE
Addition of BeReal and Revolut

### PR DESCRIPTION
**Pull request by lbr-dev**
I would like to add BeReal, very popular site mainly in the EU. Also maybe Revolut as it support donation link directly to owners bank account.

### CODE REVIEW

**Comment by sethcottle** [comment]
Hello! Sorry for the late reply on this, had a busy few weeks!

You'll need to add a white stroke to BeReal to make it more accessible on the dark mode background.

image

The image you used is appearing smaller than others with Revolut, looks like it's dimensions are pretty large in width and with it's padding. This should be scoped down to 24x24 or a 1:1 ratio. This also seems to be using the old Revolut, so I would update that with their most up to date guidelines on branding, make the button `#191C1F`, make sure it has a white stroke, and here is a SVG of their logo in white.

revolut

Guidelines: https://developer.revolut.com/docs/resources/marketing-assets-guidelines/marketing-guidelines

**Comment by lbr-dev** [comment]
Thanks for your help :)
I edited BeReal button with white stroke but I cannot find svc format (or any other higher resolution format) of BeReal logo just with letter "B." This .ico format of logo is a bit off in terms of color so I edited the background to blend in nicely:
From:
Screenshot 2024-02-21 at 22 38 48
To:
Screenshot 2024-02-21 at 22 44 56

Also as you suggested I added new Revolut logo. But I think the combination of black text and white background is more recognizable for Revolut.

Thank you for your time, this is one of my first projects on this platform. I personally used Revolut and BeReal for my own littlelink for a while and I wanted to help expand the main repo :)

**Comment by sethcottle** [comment]
This is awesome, thank you so much for pulling this together. I'm going to be annoying and have you do two more things, haha. 
1.) Bump the stroke on Revolut to 1px, instead of 2px to keep it consistent across the other button styles. On that, their official outline button also uses 1px stroke, so it would also be good to align there. See here:

image

2.) For the sake of keeping what we can scalable through vectors, and not include a new extension type in icons for users to try to remember, I recreated the BeReal favicon as an SVG using their official SVG logo. 

bereal

Get both of these changes in and I will approve this PR! Thanks for hanging in there with me!

**Comment by lbr-dev** [comment]
Thanks again for your help with all of this. Hope I fixed all the things you addressed. Recreating BeReal logo from the logo on top of their website was a brilliant idea. I did not think about that possibility. 
Thanks for your time and patience with me :)

**Comment by sethcottle** [comment]
Perfectionnnn, merged! Thanks again, appreciate you!

**Pull request merged**
